/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrs;

/**
 *
 * @author Im_jay
 */
import java.util.*;
import java.io.*;

public class Confirmation extends javax.swing.JFrame {

    /**
     * Creates new form Confirmation
     */
    public Confirmation() {
        initComponents();
        this.setLocationRelativeTo(null);
        try{
            FileReader read3 = new FileReader("confirmation.txt");
            FileReader read = new FileReader("temp.txt");
            FileReader read1 = new FileReader("hotel.txt");
            FileReader read2 = new FileReader("cost.txt");
            BufferedReader br = new BufferedReader(read);
            BufferedReader br1 = new BufferedReader(read1);
            BufferedReader br2 = new BufferedReader(read2);
            BufferedReader br3 = new BufferedReader(read3);
            jTextArea1.read(br, read);
            jTextArea2.read(br1, read1);
            jTextArea3.read(br2, read2);
            jTextArea4.read(br3, read3);
            br.close();
            br1.close();
            br2.close();
            br3.close();
            jTextArea1.requestFocus();
            jTextArea2.requestFocus();
            jTextArea3.requestFocus();
            jTextArea4.requestFocus();
        }catch(IOException e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        jTextArea3 = new javax.swing.JTextArea();
        jTextArea4 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jPanel1.add(jTextArea1);
        jTextArea1.setBounds(20, 50, 360, 120);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jPanel1.add(jTextArea2);
        jTextArea2.setBounds(20, 170, 360, 110);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jPanel1.add(jTextArea3);
        jTextArea3.setBounds(20, 280, 360, 110);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jPanel1.add(jTextArea4);
        jTextArea4.setBounds(20, 10, 360, 40);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 420, 130, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\HRS\\backgroud image.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            FileReader read = new FileReader("confirmationNum.txt");
            FileReader read2 = new FileReader("usernametemp.txt");
            BufferedReader br = new BufferedReader(read);
            BufferedReader br2 = new BufferedReader(read2);
            String conf = br.readLine();
            String confirm = conf + ".txt";
            String username = br2.readLine();
            String loc = username + "/";
            FileWriter w = new FileWriter(loc + confirm, true);
            w.write(jTextArea4.getText());
            w.write("\r\n");
            w.write("\r\n");
            w.write("\r\n");
            w.write(jTextArea1.getText());
            w.write("\r\n");
            w.write("\r\n");
            w.write(jTextArea2.getText());
            w.write("\r\n");
            w.write("\r\n");
            w.write(jTextArea3.getText());
            w.write("\r\n");
            w.write("\r\n");
            w.close();
            FileWriter w2 = new FileWriter(loc +"temp.txt",false);
            w2.write(loc+confirm);
            w2.close();
            FileWriter w3 = new FileWriter(loc +"room.txt",false);
            Random r = new Random();
            int roomNum = 100 + r.nextInt(400);
            w3.write("Room Number: "+ roomNum);
            w3.write("\r\n");
            int code = 1000+ r.nextInt(8999);
            w3.write("Room Key Code: "+ code);
            w3.close();
            br.close();
            br2.close();
            dispose();
            Profile p = new Profile();
            p.setVisible(true);
        }catch(IOException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Confirmation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    // End of variables declaration//GEN-END:variables
}
