/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrs;

import java.io.*;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Im_jay
 */
public class Filter extends javax.swing.JFrame {

    /**
     * Creates new form Filter
     */
    public Filter() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 250, 0, 0);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jRadioButton1.setText("smoking");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(70, 220, 110, 27);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jRadioButton2.setText("non-smoking");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(200, 220, 107, 27);

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jRadioButton3.setText("pet");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(70, 310, 120, 27);

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jRadioButton4.setText("no pet");
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(210, 310, 65, 27);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 390, 100, 27);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setText("Room Type");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 70, 150, 32);

        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setText("Single");
        jPanel1.add(jRadioButton5);
        jRadioButton5.setBounds(70, 120, 80, 23);

        buttonGroup3.add(jRadioButton6);
        jRadioButton6.setText("Double");
        jPanel1.add(jRadioButton6);
        jRadioButton6.setBounds(170, 120, 80, 23);

        buttonGroup3.add(jRadioButton7);
        jRadioButton7.setText("Luxury");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton7);
        jRadioButton7.setBounds(270, 120, 90, 23);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel6.setText("Smoking condition");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 170, 240, 32);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setText("Pet allowed");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 270, 160, 32);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton2.setText("<<back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 10, 100, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\HRS\\backgroud image.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //jButton1 = confirm button
        try{
            FileReader read = new FileReader("day.txt");
            BufferedReader br = new BufferedReader(read);
            String line = br.readLine();
            int d = Integer.parseInt(line);
            NumberFormat n = NumberFormat.getCurrencyInstance(Locale.US);
            int cost;
            double tax;
            double total;
            int smoke;
            FileWriter w = new FileWriter("cost.txt",false);
            if(!jRadioButton5.isSelected()&&!jRadioButton6.isSelected()&&!jRadioButton7.isSelected()){
                JOptionPane.showMessageDialog(null,"You must selected a button from room type.", "HRS",JOptionPane.PLAIN_MESSAGE);
            }
            else if(!jRadioButton1.isSelected()&&!jRadioButton2.isSelected()){
                JOptionPane.showMessageDialog(null,"You must select a button from smoking condition.", "HRS",JOptionPane.PLAIN_MESSAGE);
            }
            else if(!jRadioButton3.isSelected()&&!jRadioButton4.isSelected()){
                JOptionPane.showMessageDialog(null,"You must select a button from pet allowed.", "HRS",JOptionPane.PLAIN_MESSAGE);
            }
            else{
            if (jRadioButton5.isSelected()){
                int s = 58;
                cost = s*d;
                tax = cost*0.08;
                total = cost + tax;
                w.write("Single room per night:   $"+s);
                w.write("\r\n");
                w.write("Estimate cost of "+ d +" days: $"+ cost);
                w.write("\r\n");
                w.write("Tax:                                "+n.format(tax));
                w.write("\r\n");
                w.write("Total cost:                      "+n.format(total));
                w.write("\r\n");
                if(jRadioButton1.isSelected()){
                    w.write("Room type:                     Smoking");
                    if(jRadioButton3.isSelected()){
                        w.write(" ,with pet.");
                        w.write("\r\n");
                    }
                    else if(jRadioButton1.isSelected()){
                        w.write(" ,with no pet.");
                        w.write("\r\n");
                    }
                }
                else if(jRadioButton2.isSelected()){
                    w.write("Room type:                     non-smoking");
                    if(jRadioButton3.isSelected()){
                        w.write(" ,with pet.");
                        w.write("\r\n");
                    }
                    else if(jRadioButton1.isSelected()){
                        w.write(" ,with no pet.");
                        w.write("\r\n");
                    }
                }
            }
            else if (jRadioButton6.isSelected()){
                int s = 70;
                cost = s*d;
                tax = cost*0.08;
                total = cost + tax;
                w.write("Double room per night:  $"+s);
                w.write("\r\n");
                w.write("Estimate cost of "+ d +" days: $"+cost);
                w.write("\r\n");
                w.write("Tax:                                "+n.format(tax));
                w.write("\r\n");
                w.write("Total cost:                      "+n.format(total));
                w.write("\r\n");
                if(jRadioButton1.isSelected()){
                    w.write("Room type:                     Smoking");
                    if(jRadioButton3.isSelected()){
                        w.write(" ,with pet.");
                        w.write("\r\n");
                    }
                    else if(jRadioButton1.isSelected()){
                        w.write(" ,with no pet.");
                        w.write("\r\n");
                    }
                }
                else if(jRadioButton2.isSelected()){
                    w.write("Room type:                     non-smoking");
                    if(jRadioButton3.isSelected()){
                        w.write(" ,with pet.");
                        w.write("\r\n");
                    }
                    else if(jRadioButton1.isSelected()){
                        w.write(" ,with no pet.");
                        w.write("\r\n");
                    }
                }
            }
            else if (jRadioButton7.isSelected()){
                int s = 90;
                cost = s*d;
                tax = cost*0.08;
                total = cost + tax;
                w.write("Luxury room per night:  $"+s);
                w.write("\r\n");
                w.write("Estimate cost of "+ d +" days: $"+ cost);
                w.write("\r\n");
                w.write("Tax:                                "+n.format(tax));
                w.write("\r\n");
                w.write("Total cost:                      "+n.format(total));
                w.write("\r\n");
                if(jRadioButton1.isSelected()){
                    w.write("Room type:                     Smoking");
                    if(jRadioButton3.isSelected()){
                        w.write(" ,with pet.");
                        w.write("\r\n");
                    }
                    else if(jRadioButton1.isSelected()){
                        w.write(" ,with no pet.");
                        w.write("\r\n");
                    }
                }
                else if(jRadioButton2.isSelected()){
                    w.write("Room type:                     non-smoking");
                    if(jRadioButton3.isSelected()){
                        w.write(" ,with pet.");
                        w.write("\r\n");
                    }
                    else if(jRadioButton1.isSelected()){
                        w.write(" ,with no pet.");
                        w.write("\r\n");
                    }
                }
            }
            br.close();
            w.close();
            
            dispose();
            Cost c = new Cost();
            c.setVisible(true);
            }
        }catch(IOException e){
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Hotel h = new Hotel();
        h.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Filter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    // End of variables declaration//GEN-END:variables
}
