/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrs;

/**
 *
 * @author Im_jay
 */
import java.io.*;
import java.util.*;
import javax.swing.JOptionPane;

public class Hotel extends javax.swing.JFrame {

    /**
     * Creates new form Hotel
     */
    public Hotel() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setText("Hotel");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 10, 80, 32);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Courtyard Atlanta Downtown");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(10, 40, 330, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("W Atlanta - Downtown");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(10, 70, 330, 23);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Hampton Inn & Suites Atlanta-Downtown");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(10, 100, 330, 23);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Holiday Inn Express & Suites");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(10, 130, 330, 23);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Quality Hotel Downtown");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton5);
        jRadioButton5.setBounds(10, 160, 330, 23);

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Fairfield Inn & Suites Atlanta Downtown");
        jPanel1.add(jRadioButton6);
        jRadioButton6.setBounds(10, 190, 330, 23);

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("Motel 6 Atlanta");
        jPanel1.add(jRadioButton7);
        jRadioButton7.setBounds(10, 220, 330, 23);

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("The Westin Peachtree Plaza, Atlanta");
        jPanel1.add(jRadioButton8);
        jRadioButton8.setBounds(10, 250, 330, 23);

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setText("Hilton Garden Inn Atlanta Downtown");
        jPanel1.add(jRadioButton9);
        jRadioButton9.setBounds(10, 280, 330, 23);

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setText("Atlanta Marriott Marquis");
        jPanel1.add(jRadioButton10);
        jRadioButton10.setBounds(10, 310, 330, 23);

        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setText("DoubleTree by Hilton Hotel Atlanta Downtown");
        jPanel1.add(jRadioButton11);
        jRadioButton11.setBounds(10, 340, 330, 23);

        buttonGroup1.add(jRadioButton12);
        jRadioButton12.setText("Aloft Atlanta Downtown");
        jPanel1.add(jRadioButton12);
        jRadioButton12.setBounds(10, 370, 330, 23);

        buttonGroup1.add(jRadioButton13);
        jRadioButton13.setText("Residence Inn Atlanta Downtown");
        jPanel1.add(jRadioButton13);
        jRadioButton13.setBounds(10, 400, 330, 23);

        buttonGroup1.add(jRadioButton14);
        jRadioButton14.setText("Hyatt Place Atlanta/Downtown");
        jPanel1.add(jRadioButton14);
        jRadioButton14.setBounds(10, 430, 330, 23);

        buttonGroup1.add(jRadioButton15);
        jRadioButton15.setText("Hotel Indigo Atlanta Downtown");
        jPanel1.add(jRadioButton15);
        jRadioButton15.setBounds(10, 460, 330, 23);

        buttonGroup1.add(jRadioButton16);
        jRadioButton16.setText("Omni Atlanta Hotel at CNN Center");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton16);
        jRadioButton16.setBounds(10, 490, 330, 20);

        buttonGroup1.add(jRadioButton17);
        jRadioButton17.setText("The Ellis Hotel");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton17);
        jRadioButton17.setBounds(10, 520, 330, 23);

        buttonGroup1.add(jRadioButton18);
        jRadioButton18.setText("Sheraton Atlanta Hotel");
        jPanel1.add(jRadioButton18);
        jRadioButton18.setBounds(10, 550, 330, 23);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(390, 560, 97, 27);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 0, 97, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\HRS\\backgroud image.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //jButton1 =confirm button
        try{
        if(!jRadioButton1.isSelected()&& !jRadioButton2.isSelected()&&!jRadioButton3.isSelected()&&!jRadioButton4.isSelected()&&!jRadioButton5.isSelected()&&!jRadioButton6.isSelected()&&!jRadioButton7.isSelected()&&!jRadioButton8.isSelected()&&!jRadioButton9.isSelected()&&!jRadioButton10.isSelected()&&!jRadioButton11.isSelected()&&!jRadioButton12.isSelected()&&!jRadioButton13.isSelected()&&!jRadioButton14.isSelected()&&!jRadioButton15.isSelected()&&!jRadioButton16.isSelected()&&!jRadioButton17.isSelected()&&!jRadioButton18.isSelected()){
             JOptionPane.showMessageDialog(null,"You must selected a hotel.", "HRS",JOptionPane.PLAIN_MESSAGE);   
        }
        else{
            FileWriter w = new FileWriter("hotel.txt",false);
            if (jRadioButton1.isSelected()){
                w.write("Courtyard Atlanta Downtown");
                w.write("\r\n");
                w.write("33 Carnegie Way NW, Atlanta, GA 30303");
                w.write("\r\n");
                w.write("(404) 222-2416");
                w.write("\r\n");
            }
            else if (jRadioButton2.isSelected()){
                w.write("W Atlanta - Downtown");
                w.write("\r\n");
                w.write("45 Ivan Allen Jr Blvd NW, Atlanta, GA 30308");
                w.write("\r\n");
                w.write("(404) 582-5800");
                w.write("\r\n");
            }
            else if (jRadioButton3.isSelected()){
                w.write("Hampton Inn & Suites Atlanta-Downtown");
                w.write("\r\n");
                w.write("161 Spring St NW, Atlanta, GA 30303");
                w.write("\r\n");
                w.write("(404) 589-1111");
                w.write("\r\n");
            }
            else if (jRadioButton4.isSelected()){
                w.write("Holiday Inn Express & Suites");
                w.write("\r\n");
                w.write("111 Cone St NW, Atlanta, GA 30303");
                w.write("\r\n");
                w.write("(404) 524-7000");
                w.write("\r\n");
            }
            else if (jRadioButton5.isSelected()){
                w.write("Quality Hotel Downtown");
                w.write("\r\n");
                w.write("89 Luckie St NW, Atlanta, GA 30303");
                w.write("\r\n");
                w.write("(404) 524-7991");
                w.write("\r\n");
            }
            else if (jRadioButton6.isSelected()){
                w.write("Fairfield Inn & Suites Atlanta Downtown");
                w.write("\r\n");
                w.write("54 Peachtree St SW, Atlanta, GA 30303");
                w.write("\r\n");
                w.write("(678) 702-8600");
                w.write("\r\n");
            }
            else if (jRadioButton7.isSelected()){
                w.write("Motel 6 Atlanta");
                w.write("\r\n");
                w.write("311 Courtland St NE, Atlanta, GA 30303");
                w.write("\r\n");
                w.write("(404) 659-4545");
                w.write("\r\n");
            }
            else if (jRadioButton8.isSelected()){
                w.write("The Westin Peachtree Plaza, Atlanta");
                w.write("\r\n");
                w.write("210 Peachtree St NW, Atlanta, GA 30303");
                w.write("\r\n");
                w.write("(404) 659-1400");
                w.write("\r\n");
            }
            else if (jRadioButton9.isSelected()){
                w.write("Hilton Garden Inn Atlanta Downtown");
                w.write("\r\n");
                w.write("275 Baker St, Atlanta, GA 30313");
                w.write("\r\n");
                w.write("(404) 577-2001");
                w.write("\r\n");
            }
            else if (jRadioButton10.isSelected()){
                w.write("Atlanta Marriott Marquis");
                w.write("\r\n");
                w.write("265 Peachtree Center Ave NE, Atlanta, GA 30303");
                w.write("\r\n");
                w.write("(404) 521-0000");
                w.write("\r\n");
            }
            else if (jRadioButton11.isSelected()){
                w.write("DoubleTree by Hilton Hotel Atlanta Downtown");
                w.write("\r\n");
                w.write("160 Ted Turner Dr NW, Atlanta, GA 30303");
                w.write("\r\n");
                w.write("(404) 688-8600");
                w.write("\r\n");
            }
            else if (jRadioButton12.isSelected()){
                w.write("Aloft Atlanta Downtown");
                w.write("\r\n");
                w.write("300 Spring St NW, Atlanta, GA 30308");
                w.write("\r\n");
                w.write("(678) 515-0300");
                w.write("\r\n");
            }
            else if (jRadioButton13.isSelected()){
                w.write("Residence Inn Atlanta Downtown");
                w.write("\r\n");
                w.write("134 Peachtree St NW, Atlanta, GA 30303");
                w.write("\r\n");
                w.write("(404) 522-0950");
                w.write("\r\n");
            }
            else if (jRadioButton14.isSelected()){
                w.write("Hyatt Place Atlanta/Downtown");
                w.write("\r\n");
                w.write("330 Peachtree St NE, Atlanta, GA 30308");
                w.write("\r\n");
                w.write("(404) 577-1980");
                w.write("\r\n");
            }
            else if (jRadioButton15.isSelected()){
                w.write("Hotel Indigo Atlanta Downtown");
                w.write("\r\n");
                w.write("230 Peachtree St NE, Atlanta, GA 30303");
                w.write("\r\n");
                w.write("(404) 523-7600");
                w.write("\r\n");
            }
            else if (jRadioButton16.isSelected()){
                w.write("Omni Atlanta Hotel at CNN Center");
                w.write("\r\n");
                w.write("100 CNN Center NW, Atlanta, GA 30303");
                w.write("\r\n");
                w.write("(404) 659-0000");
                w.write("\r\n");
            }
            else if (jRadioButton17.isSelected()){
                w.write("The Ellis Hotel");
                w.write("\r\n");
                w.write("176 Peachtree St NE, Atlanta, GA 30303");
                w.write("\r\n");
                w.write("(404) 523-5155");
                w.write("\r\n");
            }
            else if (jRadioButton18.isSelected()){
                w.write("Sheraton Atlanta Hotel");
                w.write("\r\n");
                w.write("165 Courtland St NE, Atlanta, GA 30303");
                w.write("\r\n");
                w.write("(404) 659-6500");
                w.write("\r\n");
            }
            dispose();
            Filter f = new Filter();
            f.setVisible(true);
            w.close();
        }
        }catch(IOException e){
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Search s = new Search();
        s.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables
}
