/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrs;

/**
 *
 * @author Im_jay
 */
import java.util.*;
import java.io.*;
import javax.swing.JOptionPane;

public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Username");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 180, 80, 19);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 240, 68, 19);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        jLabel2.setText("Login");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 70, 160, 62);

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(160, 180, 130, 25);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(160, 240, 130, 20);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 300, 120, 27);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton2.setText("User Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(260, 0, 140, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\HRS\\backgroud image.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //jButton2 = Register Button
        dispose();
        Register rg = new Register();
        rg.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // jButton1 = login button
        try{
                FileWriter w = new FileWriter("usernametemp.txt",false);
                w.write(jTextField1.getText());
                w.close();
            }catch(IOException e){
                
            }
        final File parentDir = new File(jTextField1.getText());
        if(!parentDir.exists()){
            parentDir.mkdir();
        }
        
        if(jTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(null,"You must enter your username.", "HRS",JOptionPane.PLAIN_MESSAGE);
        }
        else if(jPasswordField1.getPassword().length == 0){
            JOptionPane.showMessageDialog(null,"You must enter your password.", "HRS",JOptionPane.PLAIN_MESSAGE);
        }
        else{
        try {
            FileReader file = new FileReader ("user.txt");
            FileReader file2 = new FileReader("admin.txt");
            
            BufferedReader reader = new BufferedReader(file);
            BufferedReader reader2 = new BufferedReader(file2);

            String line =null;
            String line2 =null;
            String line3 = null;
            
            String[] loginInfo = null;
            String[] loginInfo2 =null;
            String[] loginInfo3 =null;
            while(true){
                line = reader.readLine();
                line2 = reader2.readLine();
                
                if(line == null){
                    break;
                }
                loginInfo = line.split(" ");
                for(int i = 0; i < loginInfo.length; i++){
                    if((jTextField1.getText()).equals(loginInfo[i])){
                        String s = new String(jPasswordField1.getPassword());
                        if(s.equals(loginInfo[i+1])){
                            dispose();
                            Profile p = new Profile();
                            p.setVisible(true);
                            break;
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"Invalid username or password.", "HRS",JOptionPane.PLAIN_MESSAGE);
                            break;
                        }
                    }
                    else if(!(jTextField1.getText()).equals(loginInfo[i])){
                        if(line2 == null){
                            break;
                        }
                        loginInfo2 = line2.split(" ");
                        for(int j=0; j<loginInfo2.length;j++){
                            if((jTextField1.getText()).equals(loginInfo2[j])){
                                String s = new String(jPasswordField1.getPassword());
                                if(s.equals(loginInfo2[j+1])){
                                    dispose();
                                    RoomStatus ap = new RoomStatus();
                                    ap.setVisible(true);
                                    break;
                                }
                                else{
                                    JOptionPane.showMessageDialog(null,"Invalid username or password.", "HRS",JOptionPane.PLAIN_MESSAGE);
                                    break;
                                }
                            }
                        }
                    }
                }
            }
            reader.close();
            reader2.close();

        }catch (IOException e){
                 e.printStackTrace();       
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
