/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrs;


import java.util.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setText("Register");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 20, 110, 32);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("User");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(10, 60, 60, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Admin");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(80, 60, 70, 23);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setText("Admin access code");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 130, 140, 19);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("<html>\n<body>\n<p>If you are admin, please provide</p>\n<p>admin access code in order to register.</p>\n</body>\n</html>");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 80, 270, 40);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setText("First Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 170, 75, 19);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setText("Last name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 200, 80, 19);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setText("Username");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 230, 80, 20);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setText("Password");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 260, 80, 19);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setText("Confirm Password");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 290, 127, 19);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel10.setText("Email address");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 320, 110, 19);

        jTextField2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(180, 170, 150, 25);

        jTextField3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(180, 200, 150, 25);

        jTextField4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(180, 230, 150, 25);

        jTextField7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jPanel1.add(jTextField7);
        jTextField7.setBounds(180, 320, 150, 25);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(180, 260, 150, 20);
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(180, 290, 150, 20);
        jPanel1.add(jPasswordField3);
        jPasswordField3.setBounds(180, 130, 150, 20);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 380, 97, 27);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(300, 0, 97, 27);

        jLabel11.setText("(minimum 6 characters)");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 270, 150, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\HRS\\backgroud image.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //jbutton2 = login button
        dispose();
        LoginPage lg = new LoginPage();
        lg.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //jButton1 = register button
        String pwd1 = new String(jPasswordField1.getPassword());
        String pwd2 = new String(jPasswordField2.getPassword());
        String pwd3 = new String(jPasswordField3.getPassword());
        if(!jRadioButton1.isSelected() && !jRadioButton2.isSelected()){
            JOptionPane.showMessageDialog(null,"Please selected the User or Admin.", "HRS",JOptionPane.PLAIN_MESSAGE);
        }
        else if(jRadioButton2.isSelected()){
            if(pwd3.length()==0){
                JOptionPane.showMessageDialog(null,"You must enter admin access code.", "HRS",JOptionPane.PLAIN_MESSAGE);
            }
            else{
                try{
                FileReader read = new FileReader("accessCode.txt");
                FileReader read2 = new FileReader("userAdmin.txt");
                FileReader read3 = new FileReader("email.txt");
                BufferedReader br = new BufferedReader(read);
                BufferedReader br2 = new BufferedReader(read2);
                BufferedReader br3 = new BufferedReader(read3);
                
                String line = br.readLine();
                String line2 = br2.readLine();
                String line3 = br3.readLine();
                
                String[] info2 = line2.split(" ");
                String[] info3 = line3.split(" ");
                
                boolean nameBool = false;
                boolean emailBool = false;
                
                String pwd = new String(jPasswordField3.getPassword());
                
                    for(int i=0; i<info2.length; i++){
                        if(jTextField4.getText().equals(info2[i])){
                            nameBool = true;
                        }
                    }
                    
                    for(int j=0; j<info3.length; j++){
                        if(jTextField7.getText().equals(info3[j])){
                            emailBool = true;
                        }
                    }

                    if ( !line.equals(pwd)){
                        JOptionPane.showMessageDialog(null,"Invalid access code.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(jTextField2.getText().equals("")){
                        JOptionPane.showMessageDialog(null,"You must enter your first name.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(!jTextField2.getText().matches("[A-Za-z\\ \\']{2,10}")){
                        JOptionPane.showMessageDialog(null,"You must enter a valid first name.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(jTextField3.getText().equals("")){
                        JOptionPane.showMessageDialog(null,"You must enter your last name.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(!jTextField3.getText().matches("[A-Za-z\\-\\']{2,10}")){
                        JOptionPane.showMessageDialog(null,"You must enter a valid last name.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(jTextField4.getText().equals("")){
                        JOptionPane.showMessageDialog(null,"You must enter your username.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(nameBool == true){
                        JOptionPane.showMessageDialog(null,"Your username is not available.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(pwd1.length()==0){
                        JOptionPane.showMessageDialog(null,"You must enter your password.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(pwd1.length() < 6){
                        JOptionPane.showMessageDialog(null,"Password length should more than 6.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(pwd2.length()==0){
                        JOptionPane.showMessageDialog(null,"You must confirm password.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(!pwd1.equals(pwd2)){
                        JOptionPane.showMessageDialog(null,"Your confirm password doesn't match with password.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(jTextField7.getText().equals("")){
                        JOptionPane.showMessageDialog(null,"You must enter your e-mail address.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(!jTextField7.getText().matches("^[A-Z0-9a-z._%+-]+@[A-Z0-9a-z-]+\\.[A-Za-z]{2,4}$")){
                        JOptionPane.showMessageDialog(null,"You must enter a valid e-mail address.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(emailBool == true){
                        JOptionPane.showMessageDialog(null,"Your email is not available.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else{
                        try{
                            FileWriter w1 = new FileWriter("admin.txt",true);
                            FileWriter w = new FileWriter("userAdmin.txt",true);
                            FileWriter w2 = new FileWriter("email.txt",true);
                            w1.write(jTextField4.getText());
                            w1.write(" ");
                            w1.write(jPasswordField1.getPassword());
                            w1.write("\r\n");
                            w1.close();
                            w.write(jTextField4.getText());
                            w.write(" ");
                            w.close();
                            w2.write(jTextField7.getText());
                            w2.write(" ");
                            w2.close();
                        }catch(IOException e){
                            throw new NullPointerException();
                        }
                           dispose();
                           LoginPage lp = new LoginPage();
                           lp.setVisible(true); 
                        }
                br.close();
                br2.close();
                br3.close();
                }catch(IOException e){
                    throw new NullPointerException();
                }
            }
        }
        else if(jRadioButton1.isSelected()){
            try{
                FileReader read2 = new FileReader("userAdmin.txt");
                FileReader read3 = new FileReader("email.txt");
                BufferedReader br2 = new BufferedReader(read2);
                BufferedReader br3 = new BufferedReader(read3);
                
                String line2 = br2.readLine();
                String line3 = br3.readLine();
                
                String[] info2 = line2.split(" ");
                String[] info3 = line3.split(" ");
                
                boolean nameBool = false;
                boolean emailBool = false;
                
                    for(int i=0; i<info2.length; i++){
                        if(jTextField4.getText().equals(info2[i])){
                            nameBool = true;
                        }
                    }
                
                    for(int j=0; j<info3.length; j++){
                        if(jTextField7.getText().equals(info3[j])){
                            emailBool = true;
                        }
                    }
                    
                    if(jTextField2.getText().equals("")){
                        JOptionPane.showMessageDialog(null,"You must enter your first name.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(!jTextField2.getText().matches("[A-Za-z\\ \\']{2,10}")){
                        JOptionPane.showMessageDialog(null,"You must enter a valid first name.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(jTextField3.getText().equals("")){
                        JOptionPane.showMessageDialog(null,"You must enter your last name.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(!jTextField3.getText().matches("[A-Za-z\\-\\']{2,10}")){
                        JOptionPane.showMessageDialog(null,"You must enter a valid last name.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(jTextField4.getText().equals("")){
                        JOptionPane.showMessageDialog(null,"You must enter your username.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(nameBool == true){
                        JOptionPane.showMessageDialog(null,"Your username is not available.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(pwd1.length()==0){
                        JOptionPane.showMessageDialog(null,"You must enter your password.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(pwd1.length() < 6){
                        JOptionPane.showMessageDialog(null,"Password length should more than 6.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(pwd2.length()==0){
                        JOptionPane.showMessageDialog(null,"You must confirm password.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(!pwd1.equals(pwd2)){
                        JOptionPane.showMessageDialog(null,"Your confirm password doesn't match with password.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(jTextField7.getText().equals("")){
                        JOptionPane.showMessageDialog(null,"You must enter your e-mail address.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(!jTextField7.getText().matches("^[A-Z0-9a-z._%+-]+@[A-Z0-9a-z-]+\\.[A-Za-z]{2,4}$")){
                        JOptionPane.showMessageDialog(null,"You must enter a valid e-mail address.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else if(emailBool == true){
                        JOptionPane.showMessageDialog(null,"Your email is not available.", "HRS",JOptionPane.PLAIN_MESSAGE);
                    }
                    else{
                        try{
                            FileWriter w1 = new FileWriter("user.txt",true);
                            FileWriter w = new FileWriter("userAdmin.txt",true);
                            FileWriter w2 = new FileWriter("email.txt",true);
                            w1.write(jTextField4.getText());
                            w1.write(" ");
                            w1.write(jPasswordField1.getPassword());
                            w1.write("\r\n");
                            w1.close();
                            w.write(jTextField4.getText());
                            w.write(" ");
                            w.close();
                            w2.write(jTextField7.getText());
                            w2.write(" ");
                            w2.close();
                        }catch(IOException e){
                            throw new NullPointerException();
                        }
                        dispose();
                        LoginPage lp = new LoginPage();
                        lp.setVisible(true);
                    }
                    br2.close();
                    br3.close();
            }catch(IOException e){
                throw new NullPointerException();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
